config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'search' => 'orders#search'
  get 'complete' => 'orders#complete'
  resources :orders
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord

  def self.search(num)
    if num
      Order.where(["user_id like?", "%#{num}%"])
    else
      Order.all
    end
  end

end

app/models/user.rb
class User < ApplicationRecord



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  def search
    @orders = Order.search(params[:num]) # viewからの値をモデルへ流す
  end

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
    @order = Order.find(params[:id])
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)
    if @order.save
      redirect_to order_path(@order)
    else
      render :new
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:order_number, :user_id, :name, :memo)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<%= render 'layouts/nav' %>

<main role="main">
  <div class="carousel-inner">
    <div class="carousel-item active">
        <%= image_tag '22634469_l.jpg', class: "top-image-size" %>
    </div>
  </div>

  <div class="container marketing py-5">
    <h3 class= "category">皮膚科一般治療</h3>
    <div class="row">
      <div class="col-lg-4">
        <%= image_tag 'sissinn.jpeg', class: "image-trim" %>
        <h4>湿疹</h4>
      </div>
      <div class="col-lg-4">
        <%= image_tag 'atopi.jpeg', class: "image-trim" %>
        <h4>アトピー</h4>
      </div>
      <div class="col-lg-4">
        <%= image_tag 'nikibi.webp', class: "image-trim" %>
        <h4>ニキビ</h4>
      </div>
    </div>

    <h3 class= "category mt-5">実費診療</h3>
    <div class="row">
      <div class="col-lg-4">
        <%= image_tag 'pi-ring.jpeg', class: "image-trim" %>
        <h4>ピーリング</h4>
      </div>
      <div class="col-lg-4">
        <%= image_tag 'simi.jpeg', class: "image-trim" %>
        <h4>シミ治療</h4>
      </div>
      <div class="col-lg-4">
        <%= image_tag 'datumou.jpeg', class: "image-trim" %>
        <h4>脱毛</h4>
      </div>
    </div>


    <hr class="featurette-divider">

    <div class="row featurette" id="about">
      <div class="col-md-7">
        <h4 class="featurette-heading">あらゆる年齢の皮膚トラブルに対応いたします。</h4>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 500x500"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h4 class="featurette-heading">女性目線での細やかな対応を心がけております。</h4>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
      <div class="col-md-5 order-md-1">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 500x500"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h4 class="featurette-heading">駅から近く、駐車場完備、アクセス抜群です。</h4>
        <p class="lead"> Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 500x500"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>
      </div>
    </div>

    <hr class="featurette-divider">


    <h2>アクセス</h2>
    <div id='map'></div>

    <style>
    #map{
      height: 400px;
    }
    </style>

    <script>
    function initMap(){
      let map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: 34, lng: 131},
        zoom: 8
      });

// ピンを立てたい
      let marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    }

    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBlELpgLW45x4EPz5RHCI8RlkCFJcbAzkY&callback=initMap" async defer></script>



  </div><!-- /.container -->
</main>

<footer>
  <div class="ml-5 mb-5">
    <%= link_to "管理者ページ", orders_path %>
  </div>
</footer>

app/views/layouts/_admin_nav.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">皮膚皮膚科クリニック</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path ,class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "患者一覧", users_path ,class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_nav.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">皮膚皮膚科クリニック</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path ,class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#about">当院について</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#map">アクセス</a>
        </li>
      </ul>
      <span class="navbar-text">
        <%= link_to "順番予約", search_path %>
      </span>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hospital</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="mb-5">
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<% if order.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

    <ul>
    <% order.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/orders/index.html.erb
<%= render 'layouts/admin_nav' %>
<div class="container">
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">No.</th>
        <th scope="col">予約番号</th>
        <th scope="col">名前</th>
        <th scope="col">診察券番号</th>
        <th scope="col">患者詳細</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each_with_index do |order, i| %>
        <tr>
          <td><%= i + 1 %></td>
          <td><%= order.id %></td>
          <td><%= order.name %></td>
          <td><%= order.user_id %></td>
          <td>user/showへのリンク</td>
          <td><%= link_to '削除', order, method: :delete, data: { confirm: 'この患者の予約を削除します。本当によろしいですか?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orders/new.html.erb
<div class="container mt-3">
  <%= form_with(model: @order, local: true) do |f| %>
    <%= render 'form', order: @order %>

    <h3>予約ページ</h3>
    <div class="field">
      <h4>診察券番号</h4>
      <%= f.text_field :user_id %>
      <h4>なまえ</h4>
      <%= f.text_field :name %>
    </div>

    <div class="actions">
      <%= f.submit "予約番号発行" %>
    </div>
  <% end %>


  <%= link_to 'Back', search_path %>
</div>

app/views/orders/search.html.erb
<%= render 'layouts/nav' %>

<div class="container mt-3">
  <h1>順番待ち状況</h1>
  <h5>
    <font color="red">自分の順番の5番前には受付にいらしてください</font>
  </h5>

  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>順番待ち</th>
        <th>予約番号</th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each_with_index do |order, i| %>
        <tr>
          <td><%= i + 1 %></td>
          <td><%= order.id %></td>
        </tr>
      <% end %>
    </tbody>
  </table>


  <hr>
  <%= link_to '予約を取る', new_order_path %>
  <br>
  <hr>
  <%= link_to '予約を取り消す', new_order_path %>
  <br>
  <hr>
  <h5>順番待ち番号を確認するには診察券番号を入力してください</h5>
  <!--form_tagはDBの変更に関わらない時に使うとよい-->
  <%= form_tag(search_path,:method => 'get') do %>
    <%= text_field_tag :num %>
    <%= submit_tag '確認する', :name => nil %>
  <% end %>
</div>

app/views/orders/show.html.erb
<h1>あなたの予約番号は<%= @order.id %>番です。番号を控えて、５番前には受付にいらしてください。</h1>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'layouts/admin_nav' %>
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= render 'layouts/admin_nav' %>
<p id="notice"><%= notice %></p>

<h1>患者一覧</h1>

<table>
  <thead>
    <tr>
      <th>診察番号</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: '患者情報を削除します。本当によろしいですか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'layouts/admin_nav' %>
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= render 'layouts/admin_nav' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>